// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: proto/service.proto

package DistributedMutualExclusion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	RequestCriticalSection(ctx context.Context, in *RequestCriticalSectionRequest, opts ...grpc.CallOption) (*RequestCriticalSectionResponse, error)
	ReleaseCriticalSection(ctx context.Context, in *ReleaseCriticalSectionRequest, opts ...grpc.CallOption) (*ReleaseCriticalSectionResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) RequestCriticalSection(ctx context.Context, in *RequestCriticalSectionRequest, opts ...grpc.CallOption) (*RequestCriticalSectionResponse, error) {
	out := new(RequestCriticalSectionResponse)
	err := c.cc.Invoke(ctx, "/Service.Service/RequestCriticalSection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ReleaseCriticalSection(ctx context.Context, in *ReleaseCriticalSectionRequest, opts ...grpc.CallOption) (*ReleaseCriticalSectionResponse, error) {
	out := new(ReleaseCriticalSectionResponse)
	err := c.cc.Invoke(ctx, "/Service.Service/ReleaseCriticalSection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	RequestCriticalSection(context.Context, *RequestCriticalSectionRequest) (*RequestCriticalSectionResponse, error)
	ReleaseCriticalSection(context.Context, *ReleaseCriticalSectionRequest) (*ReleaseCriticalSectionResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) RequestCriticalSection(context.Context, *RequestCriticalSectionRequest) (*RequestCriticalSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCriticalSection not implemented")
}
func (UnimplementedServiceServer) ReleaseCriticalSection(context.Context, *ReleaseCriticalSectionRequest) (*ReleaseCriticalSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseCriticalSection not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_RequestCriticalSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCriticalSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).RequestCriticalSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Service.Service/RequestCriticalSection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).RequestCriticalSection(ctx, req.(*RequestCriticalSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ReleaseCriticalSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCriticalSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ReleaseCriticalSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Service.Service/ReleaseCriticalSection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ReleaseCriticalSection(ctx, req.(*ReleaseCriticalSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCriticalSection",
			Handler:    _Service_RequestCriticalSection_Handler,
		},
		{
			MethodName: "ReleaseCriticalSection",
			Handler:    _Service_ReleaseCriticalSection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
